version: "2"
services:
  elastic-job:
    image: registry.cn-hangzhou.aliyuncs.com/engine/elastic-job-lite-console:latest
    container_name: elastic-job-lite-console
    volumes:
      - ./cluster-logs/elastic-job:/home/elastic-job/logs
    ports:
      - "8899:8899"
#    env_file:
#      - ../env/nacos-ip.env
    restart: on-failure