apiVersion: v1
kind: Service
metadata:
  name: elastic-job-lite-console
  namespace: elastic-job
  labels:
    app: elastic-job-lite-console
spec:
  type: NodePort
  ports:
    - port: 8899
      nodePort: 31000
  selector:
    app: elastic-job-lite-console

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-job-lite-console
  labels:
    app: elastic-job-lite-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-job-lite-console
  template:
    metadata:
      labels:
        app: elastic-job-lite-console
    spec:
      containers:
        - name: elastic-job-lite-console
          image: registry.cn-hangzhou.aliyuncs.com/engine/elastic-job-lite-console:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8899