apiVersion: v1
kind: ReplicationController
metadata:
  name: elastic-job-lite-console
spec:
  replicas: 1
  selector:
    app: elastic-job-lite-console
  template:
    metadata:
      labels:
        app: elastic-job-lite-console
    spec:
      containers:
        - name: elastic-job-lite-console
          image: registry.cn-hangzhou.aliyuncs.com/engine/elastic-job-lite-console:latest
          ports:
            - containerPort:  8899