apiVersion: v1
kind: Service
metadata:
  name: elastic-job-lite-console
  namespace: elastic-job
  labels:
    app: elastic-job
spec:
  type: NodePort
  ports:
    - port: 8899
      nodePort: 8899
  selector:
    app: elastic-job-lite-console