apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-test
spec:
  replicas: 1
  selector:
    app: zookeeper-test
  template:
    metadata:
      labels:
        app: zookeeper-test
    spec:
      containers:
        - name: zookeeper-test
          image: 192.168.1.201:5000/zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: NodePort
  ports:
    - port: 2181
      nodePort: 30005
  selector:
    app: zookeeper
